### PR TITLE
Fix building with modern Cabal

### PR DESCRIPTION
**Pull request by nomeata**
following https://cabal.readthedocs.io/en/3.4/cabal-package.html#custom-setup-scripts

### CODE REVIEW

**Comment by nomeata** [comment]
Another one… hopefully with this on Hackage `cabal install` will work again…

**Comment by nomeata** [comment]
Thanks!

**Comment by def-** [comment]
No, thanks to you. I have uploaded it to hackage. For me locally it still doesn't work, but maybe that's just my setup?
```
$ cabal install ghc-vis
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ghc-vis-0.9.2 (user goal)
[__1] trying: svgcairo-0.13.2.1 (dependency of ghc-vis)
[__2] next goal: svgcairo:setup.Cabal (dependency of svgcairo)
[__2] rejecting: svgcairo:setup.Cabal-3.2.1.0/installed-3.2.1.0 (conflict:
svgcairo => svgcairo:setup.Cabal>=1.24 && <3.1)
[__2] skipping: svgcairo:setup.Cabal-3.4.0.0, svgcairo:setup.Cabal-3.2.1.0,
svgcairo:setup.Cabal-3.2.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=1.24 && <3.1' from
'svgcairo')
[__2] rejecting: svgcairo:setup.Cabal-3.0.2.0, svgcairo:setup.Cabal-3.0.1.0,
svgcairo:setup.Cabal-3.0.0.0, svgcairo:setup.Cabal-2.4.1.0,
svgcairo:setup.Cabal-2.4.0.1, svgcairo:setup.Cabal-2.4.0.0,
svgcairo:setup.Cabal-2.2.0.1, svgcairo:setup.Cabal-2.2.0.0,
svgcairo:setup.Cabal-2.0.1.1, svgcairo:setup.Cabal-2.0.1.0,
svgcairo:setup.Cabal-2.0.0.2, svgcairo:setup.Cabal-1.24.2.0,
svgcairo:setup.Cabal-1.24.0.0, svgcairo:setup.Cabal-1.22.8.0,
svgcairo:setup.Cabal-1.22.7.0, svgcairo:setup.Cabal-1.22.6.0,
svgcairo:setup.Cabal-1.22.5.0, svgcairo:setup.Cabal-1.22.4.0,
svgcairo:setup.Cabal-1.22.3.0, svgcairo:setup.Cabal-1.22.2.0,
svgcairo:setup.Cabal-1.22.1.1, svgcairo:setup.Cabal-1.22.1.0,
svgcairo:setup.Cabal-1.22.0.0, svgcairo:setup.Cabal-1.20.0.4,
svgcairo:setup.Cabal-1.20.0.3, svgcairo:setup.Cabal-1.20.0.2,
svgcairo:setup.Cabal-1.20.0.1, svgcairo:setup.Cabal-1.20.0.0,
svgcairo:setup.Cabal-1.18.1.7, svgcairo:setup.Cabal-1.18.1.6,
svgcairo:setup.Cabal-1.18.1.5, svgcairo:setup.Cabal-1.18.1.4,
svgcairo:setup.Cabal-1.18.1.3, svgcairo:setup.Cabal-1.18.1.2,
svgcairo:setup.Cabal-1.18.1.1, svgcairo:setup.Cabal-1.18.1,
svgcairo:setup.Cabal-1.18.0, svgcairo:setup.Cabal-1.16.0.3,
svgcairo:setup.Cabal-1.16.0.2, svgcairo:setup.Cabal-1.16.0.1,
svgcairo:setup.Cabal-1.16.0, svgcairo:setup.Cabal-1.14.0,
svgcairo:setup.Cabal-1.12.0, svgcairo:setup.Cabal-1.10.2.0,
svgcairo:setup.Cabal-1.10.1.0, svgcairo:setup.Cabal-1.10.0.0,
svgcairo:setup.Cabal-1.8.0.6, svgcairo:setup.Cabal-1.8.0.4,
svgcairo:setup.Cabal-1.8.0.2, svgcairo:setup.Cabal-1.6.0.3,
svgcairo:setup.Cabal-1.6.0.2, svgcairo:setup.Cabal-1.6.0.1,
svgcairo:setup.Cabal-1.4.0.2, svgcairo:setup.Cabal-1.4.0.1,
svgcairo:setup.Cabal-1.4.0.0, svgcairo:setup.Cabal-1.2.4.0,
svgcairo:setup.Cabal-1.2.3.0, svgcairo:setup.Cabal-1.2.2.0,
svgcairo:setup.Cabal-1.2.1, svgcairo:setup.Cabal-1.1.6,
svgcairo:setup.Cabal-1.24.1.0 (constraint from minimum version of Cabal used
by Setup.hs requires >=3.2)
[__2] fail (backjumping, conflict set: svgcairo, svgcairo:setup.Cabal)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: svgcairo:setup.Cabal, svgcairo, cairo,
base, ghc-vis, cairo:setup.Cabal
Try running with --minimize-conflict-set to improve the error message.
```

**Comment by nomeata** [comment]
Odd. I am using ghc-8.8 and cabal-3.2. And I install into a “env-file”, not the global package data base (which is deprectated),e.g.
```
cabal install --env tmp-env-file --lib ghc-vis
```
Did you `cabal update`?

**Comment by def-** [comment]
Yes. Seems to be a problem of svgcairo with cabal-install 3.2.

**Comment by nomeata** [comment]
Odd, I wonder why it worked for me. 

But are you use that you have cabal-3.2? For me, I can’t even install it with the command you gave:
```
/tmp $ cabal install ghc-vis
Resolving dependencies...
Up to date
cabal: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>
/tmp $ cabal install ghc-vis --installdir=/tmp/
Resolving dependencies...
Up to date
Warning: You asked to install executables, but there are no executables in
target: ghc-vis. Perhaps you want to use --lib to install libraries instead.
/tmp $ 
```
(All very odd)

**Comment by def-** [comment]
```
$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.1.0 of the Cabal library 
```
Ah right, should probably have been `cabal install --lib ghc-vis`.

**Pull request merged**
